package org.akvo.afribamodkvalidator.validation

/**
 * Types of warning flags for plot boundary quality checks.
 *
 * These warnings do NOT reject plots — they flag them for review.
 * Thresholds confirmed with African Bamboo, January 2026.
 */
enum class WarningType {
    GPS_ACCURACY_LOW,
    POINT_GAP_LARGE,
    UNEVEN_SPACING,
    AREA_TOO_LARGE,
    LOW_VERTEX_COUNT
}

/**
 * A warning generated by the validation engine for a specific plot.
 *
 * @param type The category of warning
 * @param message Human-readable description for _notes API and UI display
 * @param shortText Compact machine-parseable text for dcu_validation_warnings field
 * @param value The actual measured value that triggered the warning
 */
data class PlotWarning(
    val type: WarningType,
    val message: String,
    val shortText: String,
    val value: Double
)
